from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field

class ProblemType(str, Enum):
    POTHOLE = "pothole"
    GARBAGE = "garbage"
    STREETLIGHT = "streetlight"
    DRAIN = "drain"
    OTHER = "other"

class SeverityLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"

class CivicDetectionResult(BaseModel):
    problem_type: ProblemType = Field(..., description="Detected category: pothole, garbage, streetlight, drain, or other")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence score between 0.0 and 1.0")
    severity: SeverityLevel = Field(..., description="AI-estimated visual severity: LOW, MEDIUM, HIGH, CRITICAL")
    evidence: List[str] = Field(default_factory=list, description="Concise visual observations")
    alternatives: List[str] = Field(default_factory=list, description="Alternative possible categories considered")
    needs_retake: bool = Field(default=False, description="True if image is too blurry, dark, blank, or unclear")
    suggested_department: Optional[str] = Field(None, description="Suggested department based on problem type")
    guidance_message: Optional[str] = Field(None, description="Citizen feedback or retake instruction")
    is_fallback: bool = Field(default=False, description="True if generated by local demo fallback rather than live Gemini")
